name: GitHub Event Webhook

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Send webhook to Flask app
      run: |
        curl -X POST https://YOUR_FLASK_APP_URL/webhook \
        -H "Content-Type: application/json" \
        -d '{
          "action": "${{ github.event_name }}",
          "author": "${{ github.actor }}",
          "from_branch": "${{ github.head_ref || github.ref_name }}",
          "to_branch": "${{ github.base_ref || github.ref_name }}",
          "timestamp": "${{ github.event.head_commit.timestamp || github.event.pull_request.updated_at || github.event.repository.pushed_at }}"
        }'

