name: Send Webhook to Flask

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  send-event:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook to Flask app
        run: |
          curl -X POST   https://e355-2a09-bac5-3fdc-11cd-00-1c6-b.ngrok-free.app \
          -H "Content-Type: application/json" \
          -d '{
            "action": "${{ github.event_name }}",
            "author": "${{ github.actor }}",
            "from_branch": "${{ github.head_ref || github.ref_name }}",
            "to_branch": "${{ github.base_ref || github.ref_name }}",
            "timestamp": "${{ github.event.head_commit.timestamp || github.event.pull_request.updated_at }}"
          }'
/webhook
